import { FormEvent, useState } from 'react';
import { Calendar, ExternalLink, MessageSquareText, Send } from 'lucide-react';
import { PortalPage } from '../../components/PortalPage';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui';
import { useStudentContext } from '../../hooks/useStudentContext';
import { useSupabaseQuery } from '../../hooks/useSupabaseQuery';
import { getAssignments, saveAssignmentSubmission } from '../../services/studentService';
import { formatDate, titleCase } from '../../lib/utils';

export function AssignmentsPage(){const context=useStudentContext();const assignments=useSupabaseQuery(getAssignments,[]);const [saving,setSaving]=useState('');const submit=async(event:FormEvent<HTMLFormElement>,assignmentId:string)=>{event.preventDefault();if(!context.data)return;const form=new FormData(event.currentTarget);setSaving(assignmentId);await saveAssignmentSubmission(context.data.student.id,assignmentId,String(form.get('submission_url')),'submitted');setSaving('');await assignments.reload()};if(context.loading||assignments.loading)return <LoadingState label="Loading assignments"/>;if(context.error||assignments.error)return <ErrorState message={context.error||assignments.error||undefined} onRetry={assignments.reload}/>;return <PortalPage title="Assignments" description="Review instructions, track status and submit the requested link before the due date.">{!assignments.data?.length?<EmptyState title="No assignments yet" message="Published assignments relevant to your enrollment will appear here."/>:<div className="space-y-4">{assignments.data.map(item=>{const submission=item.assignment_submissions?.[0];return <article key={item.id} className="card p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><span className="badge bg-brand-50 text-brand-700">Week {item.week}</span><span className="badge">{titleCase(submission?.status||'not_started')}</span></div><h3 className="mt-3 text-lg font-bold">{item.title}</h3><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{item.instructions}</p><div className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Calendar size={14}/>Due {formatDate(item.due_date)}</div></div>{submission?.submission_url&&<a href={submission.submission_url} target="_blank" rel="noreferrer" className="btn-secondary shrink-0">View submission<ExternalLink size={15}/></a>}</div>{submission?.feedback&&<div className="mt-5 flex gap-3 rounded-xl bg-brand-50 p-4"><MessageSquareText className="shrink-0 text-brand-600" size={18}/><div><p className="text-xs font-bold text-brand-700">INSTRUCTOR FEEDBACK</p><p className="mt-1 text-sm leading-6 text-slate-700">{submission.feedback}</p></div></div>}<form onSubmit={event=>void submit(event,item.id)} className="mt-5 flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row"><div className="flex-1"><label className="sr-only" htmlFor={`submission-${item.id}`}>Submission link</label><input id={`submission-${item.id}`} name="submission_url" type="url" className="input" defaultValue={submission?.submission_url??''} placeholder="https://github.com/… or requested submission URL" required/></div><button className="btn-primary shrink-0" disabled={saving===item.id}><Send size={15}/>{saving===item.id?'Saving…':submission?'Update submission':'Submit assignment'}</button></form></article>})}</div>}</PortalPage>}
