import { CheckCircle2, ExternalLink, FileText, Github, PlayCircle } from 'lucide-react';
import { PortalPage } from '../../components/PortalPage';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui';
import { useStudentContext } from '../../hooks/useStudentContext';
import { useSupabaseQuery } from '../../hooks/useSupabaseQuery';
import { getLessons, setLessonComplete } from '../../services/studentService';

export function LessonsPage(){const context=useStudentContext();const lessons=useSupabaseQuery(getLessons,[]);if(context.loading||lessons.loading)return <LoadingState label="Loading lessons"/>;if(context.error||lessons.error)return <ErrorState message={context.error||lessons.error||undefined} onRetry={lessons.reload}/>;if(!context.data||!lessons.data?.length)return <PortalPage title="Lessons" description="Published lesson notes and resources for your program."><EmptyState title="No lessons yet" message="Published lessons relevant to your enrollment will appear here."/></PortalPage>;const toggle=async(id:string,current:boolean)=>{await setLessonComplete(context.data!.student.id,id,!current);await lessons.reload()};return <PortalPage title="Lessons" description="Work through published lessons and mark a lesson complete when you have finished the appropriate material."><div className="space-y-4">{lessons.data.map(lesson=>{const complete=lesson.lesson_progress?.[0]?.completed??false;return <article key={lesson.id} className="card p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex gap-4"><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${complete?'bg-emerald-50 text-emerald-600':'bg-brand-50 text-brand-600'}`}>{complete?<CheckCircle2/>:<span className="text-sm font-bold">W{lesson.week}</span>}</span><div><p className="text-xs font-bold text-brand-600">WEEK {lesson.week}</p><h3 className="mt-1 text-lg font-bold">{lesson.title}</h3>{lesson.description&&<p className="mt-2 text-sm leading-6 text-slate-600">{lesson.description}</p>}</div></div><button onClick={()=>void toggle(lesson.id,complete)} className={complete?'btn-secondary shrink-0':'btn-primary shrink-0'}>{complete?'Mark incomplete':'Mark complete'}</button></div><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-4">{lesson.resource_links?.map(link=><ResourceLink key={link} href={link} label="Resource" icon={ExternalLink}/>)}{lesson.file_url&&<ResourceLink href={lesson.file_url} label="Lesson file" icon={FileText}/>} {lesson.video_url&&<ResourceLink href={lesson.video_url} label="Video" icon={PlayCircle}/>} {lesson.github_url&&<ResourceLink href={lesson.github_url} label="GitHub" icon={Github}/>}</div></article>})}</div></PortalPage>}
function ResourceLink({href,label,icon:Icon}:{href:string;label:string;icon:typeof Github}){return <a href={href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-brand-50 hover:text-brand-700"><Icon size={14}/>{label}</a>}
