import { ExternalLink, Receipt, WalletCards } from 'lucide-react';
import { DataTable, type Column } from '../../components/DataTable';
import { PortalPage } from '../../components/PortalPage';
import { EmptyState, ErrorState, LoadingState, StatCard } from '../../components/ui';
import { useStudentContext } from '../../hooks/useStudentContext';
import { useSupabaseQuery } from '../../hooks/useSupabaseQuery';
import { getPayments } from '../../services/studentService';
import { formatDate, formatPkr, titleCase } from '../../lib/utils';
import type { Payment } from '../../types';

const columns:Column<Payment>[]=[{key:'date',header:'Date',render:row=>formatDate(row.paid_at)},{key:'type',header:'Payment type',render:row=>titleCase(row.payment_type)},{key:'amount',header:'Amount',render:row=><strong>{formatPkr(Number(row.amount))}</strong>},{key:'method',header:'Method',render:row=>row.method||'Not specified'},{key:'status',header:'Status',render:row=><span className="badge">{titleCase(row.status)}</span>},{key:'receipt',header:'Receipt',render:row=>row.receipt_url?<a href={row.receipt_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-semibold text-brand-700">Open<ExternalLink size={13}/></a>:<span className="text-slate-400">Unavailable</span>}];
export function PaymentsPage(){const context=useStudentContext();const payments=useSupabaseQuery(getPayments,[]);if(context.loading||payments.loading)return <LoadingState label="Loading payment records"/>;if(context.error||payments.error)return <ErrorState message={context.error||payments.error||undefined} onRetry={payments.reload}/>;const total=Number(context.data?.enrollment.program?.total_fee??0);const paid=payments.data?.filter(x=>x.status==='paid').reduce((sum,x)=>sum+Number(x.amount),0)??0;return <PortalPage title="Payments" description="Verified fee and installment records. This page does not process online payments."><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Program total" value={formatPkr(total)} icon={WalletCards}/><StatCard label="Amount paid" value={formatPkr(paid)} icon={Receipt}/><StatCard label="Remaining balance" value={formatPkr(Math.max(0,total-paid))} icon={WalletCards}/></div><div className="mt-6"><DataTable columns={columns} rows={payments.data??[]} empty={<EmptyState title="No payment records" message="Verified registration and installment records will appear here."/>}/></div><p className="mt-4 text-xs leading-5 text-slate-500">For discrepancies, contact the academy and quote the relevant receipt number. Do not send account passwords or payment credentials.</p></PortalPage>}
