import { BookOpenCheck, CalendarCheck, ClipboardCheck, Flag, FolderCheck } from 'lucide-react';
import { PortalPage } from '../../components/PortalPage';
import { EmptyState, ErrorState, LoadingState, ProgressBar, StatCard } from '../../components/ui';
import { useStudentContext } from '../../hooks/useStudentContext';
import { useSupabaseQuery } from '../../hooks/useSupabaseQuery';
import { getAssignments, getAttendance, getLessons, getProjects } from '../../services/studentService';

export function ProgressPage(){const context=useStudentContext();const metrics=useSupabaseQuery(async()=>{const [lessons,assignments,projects,attendance]=await Promise.all([getLessons(),getAssignments(),getProjects(),getAttendance()]);const percent=(done:number,total:number)=>total?Math.round(done/total*100):0;return {lessons:percent(lessons.filter(x=>x.lesson_progress?.[0]?.completed).length,lessons.length),assignments:percent(assignments.filter(x=>['submitted','reviewed'].includes(x.assignment_submissions?.[0]?.status??'')).length,assignments.length),projects:percent(projects.filter(x=>['submitted','reviewed','completed'].includes(x.project_submissions?.[0]?.status??'')).length,projects.length),attendance:percent(attendance.filter(x=>x.status==='present'||x.status==='excused').length,attendance.length),capstone:projects.some(x=>x.title.toLowerCase().includes('capstone')&&['reviewed','completed'].includes(x.project_submissions?.[0]?.status??''))?'Complete':'Not complete'}},[]);if(context.loading||metrics.loading)return <LoadingState label="Calculating progress"/>;if(context.error||metrics.error)return <ErrorState message={context.error||metrics.error||undefined} onRetry={metrics.reload}/>;if(!context.data||!metrics.data)return <EmptyState title="No progress record" message="Progress becomes available after your active enrollment is connected."/>;return <PortalPage title="Progress" description="A clear view of completion across lessons, submissions, attendance and capstone work."><section className="card p-6 sm:p-8"><ProgressBar value={context.data.enrollment.progress_percentage} label="Overall program progress"/><p className="mt-3 text-xs leading-5 text-slate-500">Overall progress is maintained as an official enrollment record. Activity breakdowns below are calculated from your current portal records.</p></section><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={BookOpenCheck} label="Lesson completion" value={metrics.data.lessons}/><Metric icon={ClipboardCheck} label="Assignment completion" value={metrics.data.assignments}/><Metric icon={FolderCheck} label="Project completion" value={metrics.data.projects}/><Metric icon={CalendarCheck} label="Attendance" value={metrics.data.attendance}/><StatCard icon={Flag} label="Capstone status" value={metrics.data.capstone}/></div></PortalPage>}
function Metric({icon,label,value}:{icon:typeof Flag;label:string;value:number}){return <div className="card p-5"><StatCard icon={icon} label={label} value={`${value}%`}/><div className="mt-4"><ProgressBar value={value}/></div></div>}
