import type { ReactNode } from 'react';
import { AlertCircle, ArrowRight, BookOpen, Inbox, LoaderCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ApplyLink } from './ApplyLink';

export function PageHeader({ eyebrow, title, description, children }: { eyebrow?: string; title: string; description: string; children?: ReactNode }) { return <section className="border-b border-slate-200 bg-slate-50"><div className="container-shell py-14 sm:py-20">{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h1 className="max-w-4xl text-4xl font-extrabold leading-tight sm:text-5xl">{title}</h1><p className="section-copy">{description}</p>{children && <div className="mt-7 flex flex-wrap gap-3">{children}</div>}</div></section>; }
export function SectionHeading({ eyebrow, title, copy, center = false }: { eyebrow?: string; title: string; copy?: string; center?: boolean }) { return <div className={center ? 'mx-auto mb-10 max-w-3xl text-center' : 'mb-10 max-w-3xl'}>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2 className="section-title">{title}</h2>{copy && <p className={`section-copy ${center ? 'mx-auto' : ''}`}>{copy}</p>}</div>; }
export function CTASection({ title = 'Ready to build practical technology skills?', copy = 'Explore a structured pathway and submit your application when you are ready.' }: { title?: string; copy?: string }) { return <section className="section-pad"><div className="container-shell"><div className="overflow-hidden rounded-3xl bg-navy-900 px-6 py-12 text-center shadow-glow sm:px-12"><span className="text-sm font-bold uppercase tracking-[.18em] text-brand-500">Learn. Build. Innovate.</span><h2 className="mx-auto mt-4 max-w-3xl text-3xl font-bold text-white sm:text-4xl">{title}</h2><p className="mx-auto mt-4 max-w-2xl text-slate-300">{copy}</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/programs" className="btn-secondary border-white/20 bg-white/10 text-white hover:bg-white/15 hover:text-white">Explore Programs<ArrowRight size={17} /></Link><ApplyLink>Apply for Admission</ApplyLink></div></div></div></section>; }
export function LoadingState({ label = 'Loading' }: { label?: string }) { return <div className="grid min-h-48 place-items-center rounded-2xl border border-slate-200 bg-white p-8 text-center"><div><LoaderCircle className="mx-auto animate-spin text-brand-600" /><p className="mt-3 text-sm text-slate-500">{label}…</p></div></div>; }
export function ErrorState({ message = 'Something went wrong.', onRetry }: { message?: string; onRetry?: () => void }) { return <div className="rounded-2xl border border-red-200 bg-red-50 p-8 text-center"><AlertCircle className="mx-auto text-red-600" /><h3 className="mt-3 font-semibold text-red-900">Unable to load</h3><p className="mt-1 text-sm text-red-700">{message}</p>{onRetry && <button onClick={onRetry} className="btn-secondary mt-4">Try again</button>}</div>; }
export function EmptyState({ title, message, action }: { title: string; message: string; action?: ReactNode }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><Inbox className="mx-auto text-slate-400" /><h3 className="mt-3 font-semibold">{title}</h3><p className="mx-auto mt-1 max-w-md text-sm text-slate-500">{message}</p>{action && <div className="mt-4">{action}</div>}</div>; }
export function StatCard({ label, value, icon: Icon = BookOpen, hint }: { label: string; value: ReactNode; icon?: React.ElementType; hint?: string }) { return <div className="card p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-navy-900">{value}</p>{hint && <p className="mt-1 text-xs text-slate-500">{hint}</p>}</div><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><Icon size={20} /></span></div></div>; }
export function ProgressBar({ value, label }: { value: number; label?: string }) { const safe = Math.max(0, Math.min(100, value)); return <div>{label && <div className="mb-2 flex justify-between text-sm"><span className="font-medium text-slate-700">{label}</span><span className="font-semibold text-brand-700">{safe}%</span></div>}<div className="h-2.5 overflow-hidden rounded-full bg-slate-200" role="progressbar" aria-valuenow={safe} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-brand-600 transition-all" style={{ width: `${safe}%` }} /></div></div>; }
