import { FormEvent, useState } from 'react';
import { Mail, MapPin, MessageCircle, Send } from 'lucide-react';
import { PageHeader } from '../../components/ui';
import { env } from '../../lib/env';
import { usePageMeta } from '../../hooks/usePageMeta';

export function ContactPage(){
  usePageMeta('Contact','Contact Codeliqo Academy about programs, admissions and online learning.');
  const [notice,setNotice]=useState('');
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!env.academyEmail){setNotice('Contact form delivery is not configured yet. Please use an available contact method.');return;}const data=new FormData(event.currentTarget);const subject=encodeURIComponent(`Academy inquiry: ${String(data.get('subject'))}`);const body=encodeURIComponent(`Name: ${String(data.get('name'))}\nEmail: ${String(data.get('email'))}\n\n${String(data.get('message'))}`);window.location.href=`mailto:${env.academyEmail}?subject=${subject}&body=${body}`;setNotice('Your email application should open with the inquiry ready to send.');};
  const whatsapp=env.whatsappNumber.replace(/\D/g,'');
  return <><PageHeader eyebrow="Contact" title="Start with a clear question" description="Ask about program fit, prerequisites, available batches or the admissions process. Do not send passwords, payment account details or other sensitive information."/><section className="section-pad"><div className="container-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><aside><h2 className="text-2xl font-bold">Contact the academy</h2><p className="mt-3 text-sm leading-6 text-slate-600">Codeliqo is an online academy. Available contact methods are shown only when configured by the academy.</p><div className="mt-6 space-y-3"><ContactMethod icon={MapPin} label="Location" value="Online Academy"/>{env.academyEmail&&<ContactMethod icon={Mail} label="Email" value={env.academyEmail} href={`mailto:${env.academyEmail}`}/>} {whatsapp&&<ContactMethod icon={MessageCircle} label="WhatsApp" value="Message the academy" href={`https://wa.me/${whatsapp}`}/>}</div></aside><form onSubmit={submit} className="card p-6 sm:p-8"><h2 className="text-2xl font-bold">Send an inquiry</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Name" name="name" required/><Field label="Email" name="email" type="email" required/><div className="sm:col-span-2"><label className="label" htmlFor="subject">Subject</label><select id="subject" name="subject" className="input" required><option value="Program guidance">Program guidance</option><option value="Admissions">Admissions</option><option value="Student support">Student support</option><option value="Certificate verification">Certificate verification</option><option value="General inquiry">General inquiry</option></select></div><div className="sm:col-span-2"><label className="label" htmlFor="message">Message</label><textarea id="message" name="message" className="input min-h-36 resize-y" required placeholder="How can the academy help?"/></div></div><button type="submit" className="btn-primary mt-6"><Send size={16}/>Prepare email</button>{notice&&<p role="status" className="mt-4 rounded-lg bg-slate-50 p-3 text-sm text-slate-600">{notice}</p>}</form></div></section></>;
}
function ContactMethod({icon:Icon,label,value,href}:{icon:typeof Mail;label:string;value:string;href?:string}){const inner=<><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><Icon size={19}/></span><span><span className="block text-xs text-slate-500">{label}</span><span className="block text-sm font-semibold text-navy-900">{value}</span></span></>;return href?<a href={href} target={href.startsWith('http')?'_blank':undefined} rel="noreferrer" className="flex items-center gap-3 rounded-xl border border-slate-200 p-4 hover:border-brand-300">{inner}</a>:<div className="flex items-center gap-3 rounded-xl border border-slate-200 p-4">{inner}</div>}
function Field({label,name,type='text',required}:{label:string;name:string;type?:string;required?:boolean}){return <div><label className="label" htmlFor={name}>{label}</label><input id={name} name={name} type={type} required={required} className="input"/></div>}
