import { ArrowRight, BarChart3, Blocks, BookOpen, Bot, BriefcaseBusiness, CheckCircle2, Code2, FilePenLine, FolderGit2, GraduationCap, ListChecks, Presentation, Radio, Route, Send, TrendingUp, UserPlus, Users2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ApplyLink } from '../../components/ApplyLink';
import { ProgramCard } from '../../components/ProgramCard';
import { CTASection, EmptyState, ErrorState, LoadingState, SectionHeading } from '../../components/ui';
import { useProgramCatalog } from '../../features/programs/ProgramCatalogContext';
import { faqs } from '../../data/faqs';
import { usePageMeta } from '../../hooks/usePageMeta';

const values = [
  [Radio, 'Live Instructor-Led Training', 'Engage with concepts, demonstrations and questions in focused live sessions.'],
  [Code2, 'Hands-On Practical Learning', 'Build during class and reinforce each topic through independent practice.'],
  [FolderGit2, 'Portfolio-Focused Projects', 'Turn skills into reviewed work you can explain, refine and present.'],
  [Users2, 'Small Batch Learning', 'Learn in an environment designed for participation and useful feedback.'],
  [Route, 'Structured Career Pathways', 'Follow a deliberate sequence from foundations to integrated capstone work.'],
  [BriefcaseBusiness, 'Real-World Development Skills', 'Practice the tools, workflows and problem-solving habits used in modern teams.'],
];

const journeySteps = [
  ['Choose', ListChecks],
  ['Apply', FilePenLine],
  ['Onboard', UserPlus],
  ['Learn', BookOpen],
  ['Practice', Code2],
  ['Submit', Send],
  ['Improve', TrendingUp],
  ['Present', Presentation],
] as const;

export function HomePage() {
  const { programs, loading: programsLoading, error: programsError, reload: reloadPrograms } = useProgramCatalog();
  usePageMeta('Learn. Build. Innovate.', 'Practical career-focused training in software development, data science and artificial intelligence.');
  return <>
    <section className="hero-grid relative overflow-hidden bg-navy-950 text-white">
      <div className="absolute -right-40 -top-40 size-[34rem] rounded-full bg-brand-600/20 blur-3xl" />
      <div className="container-shell relative grid min-h-[680px] items-center gap-14 py-20 lg:grid-cols-[1.08fr_.92fr]">
        <div className="animate-fade-up"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs font-semibold text-brand-100"><span className="size-1.5 rounded-full bg-brand-500" />Software Development · Data Science · Artificial Intelligence</span><p className="mt-7 text-sm font-extrabold tracking-[.19em] text-brand-500">CODELIQO ACADEMY</p><h1 className="mt-4 max-w-4xl text-5xl font-extrabold leading-[1.05] text-white sm:text-6xl lg:text-7xl">Learn. Build.<br/><span className="text-brand-500">Innovate.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">Practical career-focused training in <strong className="font-semibold text-white">Software Development, Data Science and Artificial Intelligence.</strong></p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/programs" className="btn-primary px-6">Explore Programs<ArrowRight size={17} /></Link><ApplyLink className="border border-white/15 bg-white/10 hover:bg-white/15">Apply for Admission</ApplyLink></div><p className="mt-5 text-xs text-slate-500">Applications are reviewed before enrollment is confirmed.</p></div>
        <div className="relative hidden lg:block" aria-hidden="true"><div className="mx-auto max-w-md rounded-3xl border border-white/10 bg-white/[.06] p-5 shadow-2xl backdrop-blur"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="text-sm font-semibold">Your learning pathway</span><span className="rounded-full bg-brand-500/15 px-2.5 py-1 text-xs text-brand-100">Project driven</span></div><div className="space-y-3 py-5">{[['01','Learn foundations','Clear concepts and guided examples'],['02','Build in class','Apply each concept while it is fresh'],['03','Practice independently','Develop fluency through assignments'],['04','Create a capstone','Integrate skills into portfolio work']].map(([n,t,c], i) => <div key={n} className="flex gap-4 rounded-2xl border border-white/10 bg-navy-900/60 p-4" style={{ marginLeft: `${i * 10}px` }}><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-brand-600 text-xs font-bold">{n}</span><div><p className="text-sm font-semibold">{t}</p><p className="mt-1 text-xs leading-5 text-slate-400">{c}</p></div></div>)}</div><div className="flex items-center gap-3 rounded-2xl bg-brand-600 p-4"><GraduationCap/><div><p className="text-sm font-bold">Portfolio-ready capstone</p><p className="text-xs text-brand-100">Reviewed, improved and presented</p></div></div></div></div>
      </div>
    </section>

    <section className="section-pad"><div className="container-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><SectionHeading eyebrow="Built for application" title="A technology academy centred on doing" copy="Codeliqo Academy combines structured teaching with deliberate practice. Students learn the reasoning behind modern tools, then use them to solve increasingly realistic problems."/><div className="grid gap-4 sm:grid-cols-2">{values.map(([Icon,title,copy]) => { const ValueIcon = Icon as typeof Radio; return <article key={String(title)} className="card p-5"><ValueIcon className="text-brand-600" size={23}/><h3 className="mt-4 font-bold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{String(copy)}</p></article>; })}</div></div></section>

    <section className="section-pad bg-slate-50"><div className="container-shell"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading eyebrow="Career programs" title="Practical pathways for modern technology careers." copy="Choose a focused route based on the work you want to learn and the kind of portfolio you want to build."/><Link to="/programs" className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-brand-700">Compare all programs<ArrowRight size={16}/></Link></div>{programsLoading?<LoadingState label="Loading programs"/>:programsError?<ErrorState message={programsError} onRetry={reloadPrograms}/>:programs.length?<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{programs.map((program) => <ProgramCard key={program.slug} program={program}/>)}</div>:<EmptyState title="No programs are published yet" message="Published programs will appear here automatically."/>}</div></section>

    <section className="section-pad overflow-hidden"><div className="container-shell grid gap-12 lg:grid-cols-2 lg:items-center"><div className="blueprint-grid rounded-3xl border border-brand-100 bg-brand-50 p-6 sm:p-9"><div className="rounded-2xl bg-white p-6 shadow-card"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-navy-900 text-white"><Blocks/></div><div><p className="text-xs font-bold uppercase tracking-wider text-brand-600">Learning model</p><h3 className="text-xl font-bold">Learn by building</h3></div></div><div className="mt-7 space-y-4">{['Instructor demonstration creates a clear mental model','Focused exercises turn concepts into working skill','Assignments reveal what needs more practice','Projects combine multiple skills in realistic contexts','Feedback drives revision and stronger decisions'].map((item) => <div key={item} className="flex gap-3 text-sm leading-6 text-slate-700"><CheckCircle2 className="mt-0.5 shrink-0 text-brand-600" size={18}/>{item}</div>)}</div></div></div><div><span className="eyebrow">The learning experience</span><h2 className="section-title">From guided concepts to independent work</h2><p className="section-copy">The goal is not passive exposure. Each pathway moves through demonstration, practice, submission, feedback and improvement so students learn how to think through the work—not just repeat steps.</p><div className="mt-7 grid grid-cols-3 gap-3"><MiniMetric icon={Presentation} value="Live" label="Instructor guidance"/><MiniMetric icon={BarChart3} value="Tracked" label="Learning progress"/><MiniMetric icon={FolderGit2} value="Built" label="Portfolio projects"/></div><Link to="/learning-experience" className="btn-secondary mt-7">Explore how learning works<ArrowRight size={16}/></Link></div></div></section>

    <section className="section-pad bg-navy-900"><div className="container-shell"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-brand-500">Your journey</p><h2 className="mt-4 text-3xl font-extrabold leading-tight text-white sm:text-4xl lg:text-5xl">From Application to Opportunity</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">Admissions and learning follow a transparent sequence, with each step creating the foundation for the next.</p></div><div className="mt-10 grid grid-cols-2 gap-3 sm:mt-12 sm:gap-4 md:grid-cols-4 xl:grid-cols-8">{journeySteps.map(([step, Icon],index) => <article key={step} className="flex min-h-40 min-w-0 flex-col rounded-2xl border border-white/20 bg-white/[0.06] p-5 text-left shadow-sm transition duration-300 hover:-translate-y-1 hover:border-brand-500/60 hover:bg-white/[0.09] hover:shadow-xl hover:shadow-black/15"><div className="flex items-start justify-between gap-3"><span className="text-xs font-extrabold tracking-[0.12em] text-brand-500">{String(index+1).padStart(2,'0')}</span><span className="grid size-10 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/[0.07] text-brand-500"><Icon size={19} strokeWidth={1.8}/></span></div><h3 className="mt-auto pt-6 text-base font-bold text-white sm:text-lg">{step}</h3></article>)}</div></div></section>

    <section className="section-pad"><div className="container-shell grid gap-10 lg:grid-cols-2"><div><SectionHeading eyebrow="Admissions" title="A straightforward review process" copy="Choose your pathway, share your application, and receive the relevant enrollment steps from the academy."/><ol className="space-y-3">{['Choose Program','Submit Admission Form','Application Review','Payment Instructions','Enrollment Confirmation','Student Onboarding'].map((item,index) => <li key={item} className="flex items-center gap-4 rounded-xl border border-slate-200 p-4"><span className="grid size-8 place-items-center rounded-lg bg-brand-50 text-xs font-bold text-brand-700">{index+1}</span><span className="font-semibold text-slate-800">{item}</span></li>)}</ol><ApplyLink className="mt-6">Start your application</ApplyLink></div><div><SectionHeading eyebrow="Questions" title="Helpful answers before you apply"/><div className="divide-y divide-slate-200 rounded-2xl border border-slate-200">{faqs.slice(0,5).map((faq,index) => <details key={faq.question} className="group p-5" open={index===0}><summary className="cursor-pointer list-none pr-8 font-semibold text-navy-900">{faq.question}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{faq.answer}</p></details>)}</div><Link to="/faqs" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-brand-700">View all FAQs<ArrowRight size={16}/></Link></div></div></section>
    <CTASection />
  </>;
}

function MiniMetric({ icon: Icon, value, label }: { icon: typeof Bot; value: string; label: string }) { return <div className="rounded-xl border border-slate-200 p-3"><Icon className="text-brand-600" size={18}/><p className="mt-2 text-sm font-bold">{value}</p><p className="mt-1 text-[11px] leading-4 text-slate-500">{label}</p></div>; }
