import { PageHeader } from '../../components/ui';
import { usePageMeta } from '../../hooks/usePageMeta';

const policies=[
  ['Admission Policy','Applications are reviewed for program fit, prerequisite readiness and available capacity. Submission does not confirm enrollment. Enrollment becomes active only after the academy communicates acceptance, verifies required payment and completes onboarding.'],
  ['Payment Policy','Fees must follow the schedule communicated for the selected program and batch. Payment instructions are shared privately. The portal displays verified records only; it does not process payments. Students should retain official receipts and report discrepancies promptly.'],
  ['Attendance Policy','Regular live attendance is expected because guided practice and feedback are integral to the learning model. Attendance requirements for certificate eligibility may be communicated for each batch. Students should notify the academy about unavoidable absences and complete recovery work.'],
  ['Academic Integrity Policy','Submitted work must represent the student’s own understanding and contribution. External resources, collaboration and AI assistance must follow assignment instructions and be acknowledged where required. Plagiarism, impersonation or fabricated submissions may lead to academic action.'],
  ['Student Conduct Policy','Students must communicate respectfully, protect others’ privacy and avoid disrupting learning spaces. Harassment, discrimination, misuse of systems or sharing private academy materials without permission is not acceptable.'],
  ['Assignment & Project Policy','Work should be submitted through the designated portal or method by the stated deadline. Requirements, accepted formats and review status are shown with each task. Late or revised submissions are handled according to the relevant batch instructions.'],
  ['Certificate Eligibility Policy','A Certificate of Completion may be issued when the student satisfies applicable program completion, assessment, project, attendance, conduct and payment requirements. Certificate eligibility and status are recorded by the academy and can be verified using the public certificate ID.'],
  ['Refund / Withdrawal Policy','Refund and withdrawal decisions depend on the circumstances, services already delivered and the written terms communicated for the applicable enrollment. No fixed refund period is represented on this website. Students should submit a written request; the academy will provide the currently approved terms before enrollment and review each request accordingly.'],
  ['Privacy Policy','Codeliqo collects information needed for applications, enrollment, learning delivery, academic records, payments and certificates. Access is limited according to role. Public certificate verification reveals only the certificate holder’s name, program, certificate ID, issue date and status. Private credentials and student data must not be published.'],
  ['Terms of Use','Website and portal content is provided for academy information and enrolled learning activity. Users must protect account credentials, use resources lawfully and avoid unauthorized access or distribution. Program content, schedules and operational terms may be updated with appropriate notice.'],
];
export function PoliciesPage(){usePageMeta('Policies','Review admissions, payment, attendance, academic integrity, privacy and certificate policies for Codeliqo Academy.');return <><PageHeader eyebrow="Academy policies" title="Clear expectations for a professional learning environment" description="These policies provide safe, editable baseline wording. Enrollment-specific terms communicated in writing take precedence where applicable."/><section className="section-pad"><div className="container-shell grid gap-4 lg:grid-cols-[260px_1fr]"><aside className="hidden lg:block"><nav className="sticky top-28 grid gap-1" aria-label="Policy sections">{policies.map(([title],index)=><a key={title} href={`#policy-${index}`} className="rounded-lg px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50 hover:text-brand-700">{title}</a>)}</nav></aside><div className="space-y-5">{policies.map(([title,copy],index)=><article key={title} id={`policy-${index}`} className="card scroll-mt-28 p-6 sm:p-8"><p className="text-xs font-bold text-brand-600">{String(index+1).padStart(2,'0')}</p><h2 className="mt-2 text-2xl font-bold">{title}</h2><p className="mt-4 leading-7 text-slate-600">{copy}</p></article>)}</div></div></section></>}
