import { ArrowRight, BriefcaseBusiness, Check, Clock3, Code2, ExternalLink, FileText, GraduationCap, Laptop, Radio, Route, ShieldCheck, Target, UserRoundCheck, X } from 'lucide-react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { ApplyLink } from '../../components/ApplyLink';
import { CourseTimeline } from '../../components/CourseTimeline';
import { FeeCard } from '../../components/FeeCard';
import { CTASection, ErrorState, LoadingState, SectionHeading } from '../../components/ui';
import { usePublishedProgram } from '../../features/programs/ProgramCatalogContext';
import { usePageMeta } from '../../hooks/usePageMeta';
import type { Program } from '../../types';

export function ProgramDetailPage() {
  const { slug } = useParams();
  const { program, loading, error, reload } = usePublishedProgram(slug);
  usePageMeta(program?.shortTitle ?? 'Program', program?.description ?? 'Codeliqo Academy career program.');
  if (loading) return <section className="section-pad"><div className="container-shell"><LoadingState label="Loading program"/></div></section>;
  if (error) return <section className="section-pad"><div className="container-shell"><ErrorState message={error} onRetry={reload}/></div></section>;
  if (!program) return <Navigate to="/programs" replace/>;
  const hasOverviewLists = Boolean(program.audience.length || program.outcomes.length || program.prerequisites.length);
  const hasPortfolio = Boolean(program.portfolio.length || program.capstone);
  const hasBoundaries = Boolean(program.included.length || program.excluded.length || program.bonus);
  const hasAdditionalDescription = program.fullDescription.trim() && program.fullDescription.trim() !== program.description.trim();
  return <>
    <section className="hero-grid bg-navy-950 text-white"><div className="container-shell grid gap-12 py-16 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:py-24"><div><Link to="/programs" className="text-sm font-semibold text-brand-500">Programs / {program.shortTitle}</Link><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-tight text-white sm:text-5xl">{program.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">{program.description}</p>{program.tools.length > 0 && <div className="mt-7 flex flex-wrap gap-2">{program.tools.slice(0,7).map((tool)=><span key={tool} className="rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs font-semibold text-slate-200">{tool}</span>)}</div>}<div className="mt-8 flex flex-col gap-3 sm:flex-row"><ApplyLink>Apply for Admission</ApplyLink>{program.curriculum.length > 0 && <a href="#curriculum" className="btn-secondary border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white">Explore curriculum<ArrowRight size={16}/></a>}{program.courseOutlineUrl && <a href={program.courseOutlineUrl} target="_blank" rel="noreferrer" className="btn-secondary border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white">View Course Outline<FileText size={16}/></a>}</div></div><div className="grid grid-cols-2 gap-3"><HeroFact icon={Clock3} label="Duration" value={program.duration}/><HeroFact icon={Radio} label="Live training" value={`${program.liveHours} Live Hours`}/>{program.level && <HeroFact icon={Route} label="Level" value={program.level}/>}<HeroFact icon={GraduationCap} label="Completion" value={hasPortfolio ? 'Portfolio + Capstone' : program.courseOutlineUrl ? 'Course Outline' : 'Live Course'}/></div></div></section>
    <section className="section-pad"><div className="container-shell grid gap-12 lg:grid-cols-[1fr_380px]"><div><SectionHeading eyebrow="About the course" title="A focused pathway from foundations to applied work" copy={program.description}/>{hasAdditionalDescription && <p className="-mt-5 mb-8 max-w-3xl whitespace-pre-line text-base leading-7 text-slate-600">{program.fullDescription}</p>}{hasOverviewLists && <div className="grid gap-5 md:grid-cols-2">{program.audience.length > 0 && <InfoList icon={UserRoundCheck} title="Who it is for" items={program.audience}/>} {program.outcomes.length > 0 && <InfoList icon={BriefcaseBusiness} title="Career pathways" items={program.outcomes}/>} {program.prerequisites.length > 0 && <InfoList icon={Laptop} title="Prerequisites" items={program.prerequisites}/>}<InfoList icon={Target} title="Learning approach" items={['Live demonstration and guided builds','Independent practice and submission','Feedback, revision and portfolio development']}/></div>}</div><aside><FeeCard program={program}/>{program.registrationFee > 0 && <p className="mt-3 px-2 text-xs leading-5 text-slate-500">Tuition is paid in the listed monthly installments. The registration fee is separate and included in the displayed total.</p>}</aside></div></section>
    {program.courseOutlineUrl && <section className="section-pad bg-brand-50"><div className="container-shell"><div className="flex flex-col justify-between gap-6 rounded-2xl border border-brand-100 bg-white p-6 shadow-sm sm:flex-row sm:items-center"><div className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-700"><FileText/></span><div><p className="text-xs font-extrabold uppercase tracking-wider text-brand-600">Course outline</p><h2 className="mt-1 text-xl font-bold">{program.courseOutlineName ?? 'Course Outline PDF'}</h2><p className="mt-1 text-sm text-slate-600">Open the outline for this course in a new tab.</p></div></div><a href={program.courseOutlineUrl} target="_blank" rel="noreferrer" className="btn-primary shrink-0">View Course Outline<ExternalLink size={16}/></a></div></div></section>}
    {program.tools.length > 0 && <section className="section-pad bg-slate-50"><div className="container-shell"><SectionHeading eyebrow="Technology toolkit" title="Tools you will work with" copy="Technology is introduced in the context of practical problems, with depth determined by the curriculum scope."/><div className="flex flex-wrap gap-3">{program.tools.map((tool)=><span key={tool} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm"><Code2 size={15} className="text-brand-600"/>{tool}</span>)}</div></div></section>}
    {program.curriculum.length > 0 && <section id="curriculum" className="section-pad scroll-mt-24"><div className="container-shell grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><SectionHeading eyebrow="Curriculum" title={`${program.weeks} weeks of structured progression`} copy="Open each curriculum phase to review its topics. Exposure items introduce a tool or concept without representing full mastery."/><div className="card p-5"><p className="text-sm font-bold text-navy-900">Program rhythm</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg bg-brand-50 p-3"><strong className="block text-brand-700">Learn</strong>Concepts</div><div className="rounded-lg bg-brand-50 p-3"><strong className="block text-brand-700">Build</strong>Practice</div><div className="rounded-lg bg-brand-50 p-3"><strong className="block text-brand-700">Review</strong>Improve</div></div></div></div><CourseTimeline modules={program.curriculum}/></div></section>}
    {program.slug==='full-stack' && <section className="section-pad bg-navy-900"><div className="container-shell"><SectionHeading eyebrow="Application architecture" title="How the full-stack system connects" copy="Week 31 focuses on the boundaries, responsibilities and data flow across the complete application." center/><div className="flex flex-wrap items-center justify-center gap-2">{['User','React','REST API','FastAPI','Business Logic','SQLAlchemy','PostgreSQL','API Response','React UI'].map((item,index)=><div key={item} className="flex items-center gap-2"><span className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-white">{item}</span>{index<8&&<ArrowRight size={15} className="text-brand-500"/>}</div>)}</div></div></section>}
    {hasPortfolio && <section className="section-pad bg-slate-50"><div className="container-shell"><SectionHeading eyebrow="Portfolio development" title="Evidence of applied learning" copy="Projects are designed to make your process visible: how you frame a problem, choose an approach, build, test and explain the result."/>{program.portfolio.length > 0 && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{program.portfolio.map((project,index)=><article key={project} className="card p-5"><span className="text-xs font-bold text-brand-600">PROJECT {String(index+1).padStart(2,'0')}</span><h3 className="mt-3 font-bold">{project}</h3></article>)}</div>}{program.capstone && <div className="mt-6 rounded-2xl bg-navy-900 p-7 text-white"><div className="flex gap-4"><GraduationCap className="shrink-0 text-brand-500"/><div><p className="text-xs font-bold uppercase tracking-wider text-brand-500">Capstone</p><h3 className="mt-2 text-xl font-bold text-white">Integrated final project</h3><p className="mt-2 leading-7 text-slate-300">{program.capstone}</p></div></div></div>}</div></section>}
    <section className="section-pad"><div className={`container-shell grid gap-8 ${hasBoundaries ? 'lg:grid-cols-2' : 'max-w-3xl'}`}>{hasBoundaries && <div><SectionHeading eyebrow="Program boundaries" title="Clear expectations before you enroll"/><div className="grid gap-6 sm:grid-cols-2">{program.included.length > 0 && <Boundary title="What is included" icon={Check} items={program.included} positive/>}{program.excluded.length > 0 && <Boundary title="What is not included" icon={X} items={program.excluded}/>}</div>{program.bonus&&<div className="mt-6 rounded-xl border border-brand-100 bg-brand-50 p-5"><p className="font-bold text-brand-800">Optional bonus / exposure</p><p className="mt-2 text-sm leading-6 text-slate-700">{program.bonus}</p></div>}</div>}<div><SectionHeading eyebrow="Program FAQ" title="Before you apply"/><div className="divide-y divide-slate-200 rounded-2xl border border-slate-200">{programFaqs(program).map((item,index)=><details key={item.q} className="p-5" open={index===0}><summary className="cursor-pointer list-none font-semibold">{item.q}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{item.a}</p></details>)}</div></div></div></section>
    <CTASection title={`Build your ${program.shortTitle.toLowerCase()} pathway`} copy="Review the scope, prerequisites and fee structure, then submit an application for academy review."/>
  </>;
}

function HeroFact({icon:Icon,label,value}:{icon:typeof ShieldCheck;label:string;value:string}) { return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><Icon className="text-brand-500" size={20}/><p className="mt-4 text-xs uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-bold text-white">{value}</p></div>; }
function InfoList({icon:Icon,title,items}:{icon:typeof Target;title:string;items:string[]}) { return <article className="card p-5"><Icon className="text-brand-600"/><h3 className="mt-4 font-bold">{title}</h3><ul className="mt-3 space-y-2">{items.map(item=><li key={item} className="flex gap-2 text-sm leading-6 text-slate-600"><Check size={15} className="mt-1 shrink-0 text-brand-600"/>{item}</li>)}</ul></article>; }
function Boundary({title,icon:Icon,items,positive=false}:{title:string;icon:typeof Check;items:string[];positive?:boolean}) { return <div><h3 className="font-bold">{title}</h3><ul className="mt-4 space-y-3">{items.map(item=><li key={item} className="flex gap-2 text-sm leading-6 text-slate-600"><Icon size={16} className={`mt-1 shrink-0 ${positive?'text-emerald-600':'text-slate-400'}`}/>{item}</li>)}</ul></div>; }
function programFaqs(program: Program) { return [{q:'Is this program suitable for my starting point?',a:`The program level is ${program.level}. Review the prerequisites above; if you are unsure, contact the academy before applying.`},{q:'How much live training is included?',a:`The pathway includes ${program.liveHours} hours of live training across ${program.duration.toLowerCase()}, supported by independent work.`},{q:'Does completing the program guarantee employment?',a:'No. Codeliqo Academy does not guarantee employment. The program supports skill development, portfolio work and career preparation.'},{q:'What certificate is provided?',a:'Eligible students receive a Certificate of Completion after meeting applicable academic, attendance and payment requirements.'}]; }
