import { FormEvent, useCallback, useEffect, useState } from 'react';
import { BadgeCheck, Search, ShieldCheck, XCircle } from 'lucide-react';
import { ErrorState, PageHeader } from '../../components/ui';
import { isSupabaseConfigured } from '../../lib/env';
import { supabase } from '../../lib/supabase';
import { formatDate, titleCase } from '../../lib/utils';
import type { Certificate } from '../../types';
import { usePageMeta } from '../../hooks/usePageMeta';

type PublicCertificate=Pick<Certificate,'certificate_id'|'program_name'|'issue_date'|'status'|'student_name'>;
export function VerifyCertificatePage(){
  usePageMeta('Verify Certificate','Verify a Codeliqo Academy Certificate of Completion using its certificate ID.');
  const [certificateId,setCertificateId]=useState('');const [result,setResult]=useState<PublicCertificate|null|undefined>(undefined);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const runVerification=useCallback(async(value:string)=>{setError('');setResult(undefined);if(!isSupabaseConfigured){setError('Certificate verification is not connected yet. Please try again after the academy configures its backend.');return;}setLoading(true);const normalized=value.trim().toUpperCase();const {data,error:queryError}=await supabase.rpc('verify_certificate',{lookup_id:normalized}).maybeSingle();setLoading(false);if(queryError){setError('Verification is temporarily unavailable.');return;}setResult((data as PublicCertificate|null)??null);},[]);
  useEffect(()=>{const directId=new URLSearchParams(window.location.search).get('id')?.trim().toUpperCase();if(directId){setCertificateId(directId);void runVerification(directId);}},[runVerification]);
  const verify=(event:FormEvent)=>{event.preventDefault();void runVerification(certificateId);};
  const issued=result?.status==='issued';
  return <><PageHeader eyebrow="Public verification" title="Verify a Certificate of Completion" description="Enter the complete certificate ID exactly as it appears on the certificate. Verification shows only limited, non-sensitive certificate information."/><section className="section-pad"><div className="container-shell max-w-2xl"><form onSubmit={verify} className="card p-6 sm:p-8"><label htmlFor="certificate-id" className="label">Certificate ID</label><div className="flex flex-col gap-3 sm:flex-row"><input id="certificate-id" value={certificateId} onChange={e=>setCertificateId(e.target.value.toUpperCase())} placeholder="CERT-2026-000001" required className="input font-mono uppercase"/><button disabled={loading} className="btn-primary shrink-0"><Search size={17}/>{loading?'Verifying…':'Verify Certificate'}</button></div><p className="mt-3 text-xs text-slate-500">Example format: CERT-2026-000001</p></form>{error&&<div className="mt-5"><ErrorState message={error}/></div>}{result===null&&<div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-8 text-center"><XCircle className="mx-auto text-slate-400" size={34}/><h2 className="mt-4 text-xl font-bold">Certificate Not Found</h2><p className="mt-2 text-sm text-slate-600">Check the certificate ID and try again.</p></div>}{result&&<div className={`mt-5 overflow-hidden rounded-2xl border bg-white shadow-card ${issued?'border-emerald-200':'border-red-200'}`}><div className={`flex items-center gap-4 p-6 ${issued?'bg-emerald-50':'bg-red-50'}`}>{issued?<BadgeCheck className="text-emerald-600" size={34}/>:<XCircle className="text-red-600" size={34}/>}<div><p className={`text-xs font-bold uppercase tracking-wider ${issued?'text-emerald-700':'text-red-700'}`}>{issued?'Certificate Verified':'Certificate Revoked'}</p><h2 className="mt-1 text-xl font-bold">Certificate of Completion</h2></div></div><dl className="grid gap-px bg-slate-200 sm:grid-cols-2">{[['Student Name',result.student_name??''],['Program',result.program_name],['Certificate ID',result.certificate_id??''],['Completion Date',formatDate(result.issue_date)],['Status',titleCase(result.status)]].map(([label,value])=><div key={label} className="bg-white p-5"><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="mt-1 text-sm font-bold text-navy-900">{value}</dd></div>)}</dl></div>}<div className="mt-5 flex gap-3 rounded-xl border border-brand-100 bg-brand-50 p-4"><ShieldCheck className="shrink-0 text-brand-600"/><p className="text-xs leading-5 text-slate-600">This lookup never exposes email, phone, payment details, internal student IDs or other private records.</p></div></div></section></>;
}
