import { useState } from 'react';
import { Outlet, useMatches } from 'react-router-dom';
import { Megaphone, BadgeCheck, BarChart3, BookOpen, BriefcaseBusiness, CalendarCheck, CalendarDays, ClipboardList, CreditCard, FolderKanban, GraduationCap, LayoutDashboard, MessageSquareText, UserRound, UserRoundPlus, UsersRound } from 'lucide-react';
import { DashboardHeader } from '../components/DashboardHeader';
import { DashboardSidebar, type DashboardNavItem } from '../components/DashboardSidebar';
import { usePageMeta } from '../hooks/usePageMeta';

const studentItems:DashboardNavItem[]=[['Dashboard','/student/dashboard',LayoutDashboard],['My Program','/student/my-program',GraduationCap],['Lessons','/student/lessons',BookOpen],['Assignments','/student/assignments',ClipboardList],['Projects','/student/projects',FolderKanban],['Progress','/student/progress',BarChart3],['Payments','/student/payments',CreditCard],['Certificates','/student/certificates',BadgeCheck],['Profile','/student/profile',UserRound]].map(([label,to,icon])=>({label:label as string,to:to as string,icon:icon as DashboardNavItem['icon']}));
const adminItems:DashboardNavItem[]=[['Dashboard','/admin/dashboard',LayoutDashboard],['Students','/admin/students',UsersRound],['Enrollments','/admin/enrollments',UserRoundPlus],['Programs','/admin/programs',GraduationCap],['Batches','/admin/batches',CalendarDays],['Lessons','/admin/lessons',BookOpen],['Assignments','/admin/assignments',ClipboardList],['Projects','/admin/projects',BriefcaseBusiness],['Submission Review','/admin/submissions',MessageSquareText],['Attendance','/admin/attendance',CalendarCheck],['Payments','/admin/payments',CreditCard],['Certificates','/admin/certificates',BadgeCheck],['Announcements','/admin/announcements',Megaphone]].map(([label,to,icon])=>({label:label as string,to:to as string,icon:icon as DashboardNavItem['icon']}));

export function DashboardLayout({type}:{type:'student'|'admin'}){const [open,setOpen]=useState(false);const matches=useMatches();const leaf=matches[matches.length-1];const routeTitle=typeof leaf?.handle==='object'&&leaf.handle&&'title' in leaf.handle?String((leaf.handle as {title:string}).title):type==='admin'?'Admin Dashboard':'Student Portal';usePageMeta(routeTitle,type==='admin'?'Secure Codeliqo Academy administration.':'Your secure Codeliqo Academy learning portal.');return <div className="min-h-screen bg-slate-50"><DashboardSidebar items={type==='admin'?adminItems:studentItems} open={open} onClose={()=>setOpen(false)} portal={type==='admin'?'Administration':'Student portal'}/><div className="lg:pl-72"><DashboardHeader title={routeTitle} onMenu={()=>setOpen(true)}/><main className="mx-auto max-w-[1500px] p-5 sm:p-8"><Outlet/></main></div></div>}
